services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: empire
    ports:
      - "5432:5432"
    volumes:
      - empire_db:/var/lib/postgresql/data

volumes:
  empire_db:
